### PR TITLE
Update recipe for 1.0.0 release

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
I don't understand why appveyor crashed. Also should I somehow use conda-smithy to add building for Python 3 or will it happen at a later stage.

**Comment by blink1073** [comment]
You may have to re-render the package.  `conda install conda-smithy; conda-smithy rerender`

**Comment by MatthieuDartiailh** [comment]
I re-rendered the recipe and now all tests are passing. @blink1073 if you are happy with the changes I will let you merge.

**Comment by blink1073** [comment]
👍

**Comment by MatthieuDartiailh** [comment]
Thanks @blink1073.
Do you who I should ping at Anaconda.Inc to update the recipe in the default channel ?

**Comment by blink1073** [comment]
You can open an issue [here](https://github.com/AnacondaRecipes/aggregate).  The default recipes are based on the conda-forge recipes now.

**Comment by MatthieuDartiailh** [comment]
Thanks @blink1073

**Pull request merged**
